scene:
  n_envs: 1 # shouldnt be changed
  sim:
    dt: 0.05
    substeps: 1

  show_Viewer: True

  profiling_options:
    show_FPS: false

  viewer_config:
    max_FPS: 60
    camera_fov: 40
    enable_interaction: false

  vis_config:
    show_cameras: false
    shadow: false
    plane_reflection: false
    lights:
      - type: directional
        dir: [-1, -1, -1]
        color: [1.0, 1.0, 1.0]
        intensity: 5.0

  rigid_config:
    enable_collision: true
    enable_joint_limit: true
    enable_self_collision: false
    max_collision_pairs: 300

world:
  name: plane
  world_type: plane #[plane, terrain, file]


objects:

robots:
  robot_one:
    visualize_contact: false
    namespace: "robot"
    control:
      #the control is very bad the kp and kv values must be tuned
      joint_commands_topic: joint_commands
      joint_commands_topic_frequency: 50
      joint_states_topic: joint_states
      joint_states_topic_frequency: 50
      joint_control_topic: joint_control
      joint_control_topic_frequency: 50
      joint_properties: 
        panda_joint1:
          kp: 4500
          kv: 550
          command: position
        panda_joint2:
          kp: 4500
          kv: 550
          command: position
        panda_joint3:
          kp: 3500
          kv: 450
          command: position
        panda_joint4:
          kp: 2000
          kv: 250
          command: position
        panda_joint5:
          kp: 2000
          kv: 250
          command: position
        panda_joint6:
          kp: 2000
          kv: 300
          command: position
        panda_joint7:
          kp: 100
          kv: 25
          command: position
# [4500, 4500, 3500, 3500, 2000, 2000, 2000, 100, 100]
# [450, 450, 350, 350, 200, 200, 200, 10, 10]
    morph:
      path: "src/gs_ros2_control_demos/urdf/panda_bullet/panda.urdf"
      pos: [0.0, 0.0, 0.0]
      euler: [0.0, 0.0, 0.0]
      quat: null
      visualization: true
      collision: true
      requires_jac_and_IK: true
      scale: 1.0
      convexify: null
      recompute_inertia: false
      fixed: true
      prioritize_urdf_material: false

    material:
      type: rigid
      rho: 200.0
      friction: null
      needs_coup: true
      coup_friction: 0.1
      coup_softness: 0.002
      coup_restitution: 0.0
      sdf_cell_size: 0.005
      sdf_min_res: 32
      sdf_max_res: 128
      gravity_compensation: 0

    sensors: # all the sensor configs are in the sensor_configs.yaml section
    # ----------------------------
    # CAMERA (RGB, Depth, segmentation, normal.)
    # Although multiple camera types can be specified for one section, it is recommneded to set one camera type per sensor
    # i.e. if you want RGB and Depth, create two sensors with same transform but different camera_types
    # ----------------------------
      # - name: front_cam
      #   sensor_type: cam
      #   link: lidar_link
      #   # Transform: [[  0.00,   0.00,  -1.00,   0.00],
      #   #             [ -1.00,   0.00,   0.00,   0.00],
      #   #             [  0.00,   1.00,   0.00,   0.00],
      #   #             [  0.00,   0.00,   0.00,   1.00]]
      #   pos: [0,0,0]
      #   euler: [90,0,-90]
      #   topics: [rgb]
      #   frequency: 15
      #   QOS_history: keep_last
      #   QOS_depth: 25
      #   QOS_reliability: reliable
      #   QOS_durability: volatile
      #   frame_id: lidar_link
      #   # camera_type one of : ["rgb", "depth", "segmentation", "normal"]
      #   # normal camera causes issue, idk why
      #   camera_types: [rgb]
      #   model: pinhole
      #   res: [640, 480]
      #   vfov: 30
      #   aperture: 2.8
      #   focus_dist: null
      #   GUI: false
      #   spp: 256
      #   # denoise: true
      #   near: 0.05
      #   far: 10.0
      #   add_noise: false
      #   noise_mean: 0.0
      #   noise_std: 0.01

      # - name: lidar_1
      #   sensor_type: 3d_lidar
      #   link: lidar_link
      #   frame_id: lidar_link
      #   topic: lidar_topic
      #   frequency: 10.0
      #   near: 0.3
      #   far: 100.0
      #   pos_offset: [0.0, 0.0, 0.5]
      #   euler_offset: [0.0, 0.0, 0.0]
      #   fov: [360.0, 30.0]
      #   n_points: [64, 128]
      #   draw_debug: false
      #   draw_point_radius: 0.03
      #   ray_start_color: [0.5, 0.5, 1.0, 1.0]
      #   ray_hit_color: [1.0, 0.0, 0.0, 1.0]
      #   return_points_in_world_frame: false
      #   noise_mean: 0.01
      #   noise_std: 0.02
      #   QOS_history: KEEP_LAST
      #   QOS_depth: 5
      #   QOS_reliability: RELIABLE
      #   QOS_durability: VOLATILE



  
